# Generated by Django 3.2.6 on 2021-09-11 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Département',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
                ('salaire', models.CharField(max_length=255)),
                ('date_embauche', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date embauche')),
            ],
        ),
    ]
